server.port=8083

spring.datasource.url=jdbc:postgresql://db-pedidos:5432/pedidos_db
spring.datasource.username=pedidos_user
spring.datasource.password=pedidos_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ddl-auto=update crea/actualiza la tabla solo a partir de la entidad,
# suficiente para esta tarea. En un proyecto real usarías Flyway/Liquibase.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
